--
-- PostgreSQL database dump
--

-- Dumped from database version 16.2
-- Dumped by pg_dump version 16.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: cars; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cars (
    id integer NOT NULL,
    brand character varying(255),
    model character varying(255),
    production_date date,
    price double precision,
    type character varying(255),
    country character varying(255),
    image_url character varying(255)
);


ALTER TABLE public.cars OWNER TO postgres;

--
-- Name: cars_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cars ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cars_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: cars; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cars (id, brand, model, production_date, price, type, country, image_url) FROM stdin;
1	Renault	Arkanam	2023-01-01	25000	SUV	France	resources/images/Arcanum.jpg
2	BMW	X4	2022-10-05	52000	SUV	Germany	resources/images/BMW_X4.jpg
3	BMW	8 Series	2020-10-10	80000	Coupe	Germany	resources/images/BMW_8.jpg
4	BMW	3 Series	2022-05-20	45000	Sedan	Germany	resources/images/BMW_3.jpg
5	BMW	1 Series	2023-01-01	35000	Hatchback	Germany	resources/images/BMW_1.jpg
6	Renault	Sandero Stepway	2022-07-10	19000	SUV	Romania	resources/images/Sandero_Stepway.jpg
7	Renault	Master	2020-10-10	40000	Van	France	resources/images/Master.jpg
8	BMW	X6	2021-09-28	65000	SUV	Germany	resources/images/BMW_X6.jpg
9	BMW	2 Series	2022-03-15	40000	Coupe	Germany	resources/images/BMW_2.jpg
10	BMW	5 Series	2022-09-05	55000	Sedan	Germany	resources/images/BMW_5.jpg
11	Renault	Captur	2023-02-28	28000	SUV	France	resources/images/Captur.jpg
12	BMW	7 Series	2023-02-28	70000	Sedan	Germany	resources/images/BMW_7.jpg
13	BMW	X5	2022-11-01	58000	SUV	Germany	resources/images/BMW_X5.jpg
14	BMW	X3	2022-08-10	48000	SUV	Germany	resources/images/BMW_X3.jpg
15	Renault	Logan Stepway	2022-09-05	18000	SUV	Romania	resources/images/Logan_Stepway.jpg
16	Renault	Sandero	2022-05-20	17000	Hatchback	Romania	resources/images/Sandero.jpg
17	Renault	Logan	2022-03-15	15000	Sedan	Romania	resources/images/Logan.jpg
18	BMW	X2	2023-06-20	42000	SUV	Germany	resources/images/BMW_X2.jpg
19	BMW	X1	2022-04-15	38000	SUV	Germany	resources/images/BMW_X1.jpg
20	BMW	6 Series	2021-12-01	60000	Coupe	Germany	resources/images/BMW_6.jpg
21	BMW	4 Series	2022-07-10	50000	Coupe	Germany	resources/images/BMW_4.jpg
22	Renault	Duster	2021-12-01	30000	SUV	France	resources/images/Duster.jpg
\.


--
-- Name: cars_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cars_id_seq', 27, true);


--
-- Name: cars cars_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cars
    ADD CONSTRAINT cars_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

