--
-- PostgreSQL database cluster dump
--

SET default_transaction_read_only = off;

SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

--
-- Roles
--

CREATE ROLE postgres;
ALTER ROLE postgres WITH SUPERUSER INHERIT CREATEROLE CREATEDB LOGIN REPLICATION BYPASSRLS PASSWORD 'SCRAM-SHA-256$4096:pzQWZeyE59ZustK7AjSkvw==$g/rVSl7badartalvEzehSnDaQvWuRv6pLc902tfC0No=:hm6sigTN4HPa0W6bZKZfZezf5Pao/Jg9razb2Pce6eI=';

--
-- User Configurations
--








--
-- Databases
--

--
-- Database "template1" dump
--

\connect template1

--
-- PostgreSQL database dump
--

-- Dumped from database version 16.2
-- Dumped by pg_dump version 16.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- PostgreSQL database dump complete
--

--
-- Database "auto_db" dump
--

--
-- PostgreSQL database dump
--

-- Dumped from database version 16.2
-- Dumped by pg_dump version 16.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: auto_db; Type: DATABASE; Schema: -; Owner: postgres
--

CREATE DATABASE auto_db WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'Russian_Russia.1251';


ALTER DATABASE auto_db OWNER TO postgres;

\connect auto_db

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: cars; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cars (
    id integer NOT NULL,
    brand character varying(255),
    model character varying(255),
    production_date date,
    price double precision,
    type character varying(255),
    country character varying(255),
    image_url character varying(255),
    imageurl character varying(255)
);


ALTER TABLE public.cars OWNER TO postgres;

--
-- Name: cars_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cars ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cars_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: databasechangelog; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.databasechangelog (
    id character varying(255) NOT NULL,
    author character varying(255) NOT NULL,
    filename character varying(255) NOT NULL,
    dateexecuted timestamp without time zone NOT NULL,
    orderexecuted integer NOT NULL,
    exectype character varying(10) NOT NULL,
    md5sum character varying(35),
    description character varying(255),
    comments character varying(255),
    tag character varying(255),
    liquibase character varying(20),
    contexts character varying(255),
    labels character varying(255),
    deployment_id character varying(10)
);


ALTER TABLE public.databasechangelog OWNER TO postgres;

--
-- Name: databasechangeloglock; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.databasechangeloglock (
    id integer NOT NULL,
    locked boolean NOT NULL,
    lockgranted timestamp without time zone,
    lockedby character varying(255)
);


ALTER TABLE public.databasechangeloglock OWNER TO postgres;

--
-- Data for Name: cars; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cars (id, brand, model, production_date, price, type, country, image_url, imageurl) FROM stdin;
1	Renault	Arkanam	2023-01-01	25000	SUV	France	resources/images/Arcanum.jpg	\N
20	BMW	X4	2022-10-05	52000	SUV	Germany	resources/images/BMW_X4.jpg	\N
16	BMW	8 Series	2020-10-10	80000	Coupe	Germany	resources/images/BMW_8.jpg	\N
11	BMW	3 Series	2022-05-20	45000	Sedan	Germany	resources/images/BMW_3.jpg	\N
9	BMW	1 Series	2023-01-01	35000	Hatchback	Germany	resources/images/BMW_1.jpg	\N
4	Renault	Sandero Stepway	2022-07-10	19000	SUV	Romania	resources/images/Sandero_Stepway.jpg	\N
8	Renault	Master	2020-10-10	40000	Van	France	resources/images/Master.jpg	\N
22	BMW	X6	2021-09-28	65000	SUV	Germany	resources/images/BMW_X6.jpg	\N
10	BMW	2 Series	2022-03-15	40000	Coupe	Germany	resources/images/BMW_2.jpg	\N
13	BMW	5 Series	2022-09-05	55000	Sedan	Germany	resources/images/BMW_5.jpg	\N
7	Renault	Captur	2023-02-28	28000	SUV	France	resources/images/Captur.jpg	\N
15	BMW	7 Series	2023-02-28	70000	Sedan	Germany	resources/images/BMW_7.jpg	\N
21	BMW	X5	2022-11-01	58000	SUV	Germany	resources/images/BMW_X5.jpg	\N
19	BMW	X3	2022-08-10	48000	SUV	Germany	resources/images/BMW_X3.jpg	\N
5	Renault	Logan Stepway	2022-09-05	18000	SUV	Romania	resources/images/Logan_Stepway.jpg	\N
3	Renault	Sandero	2022-05-20	17000	Hatchback	Romania	resources/images/Sandero.jpg	\N
2	Renault	Logan	2022-03-15	15000	Sedan	Romania	resources/images/Logan.jpg	\N
18	BMW	X2	2023-06-20	42000	SUV	Germany	resources/images/BMW_X2.jpg	\N
17	BMW	X1	2022-04-15	38000	SUV	Germany	resources/images/BMW_X1.jpg	\N
14	BMW	6 Series	2021-12-01	60000	Coupe	Germany	resources/images/BMW_6.jpg	\N
12	BMW	4 Series	2022-07-10	50000	Coupe	Germany	resources/images/BMW_4.jpg	\N
6	Renault	Duster	2021-12-01	30000	SUV	France	resources/images/Duster.jpg	\N
25	Chevrolet	Camaro	2024-04-24	2	Седан	Франция	/AutoCatalogSystem_war_exploded/resources/images/car_1712043908677.jpg	\N
\.


--
-- Data for Name: databasechangelog; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.databasechangelog (id, author, filename, dateexecuted, orderexecuted, exectype, md5sum, description, comments, tag, liquibase, contexts, labels, deployment_id) FROM stdin;
create-tables	pr1nkos	db/changelog.yaml	2024-04-02 11:44:55.737738	1	EXECUTED	9:d244c405af37a3cc25de7cc637f8e49b	createTable tableName=cars		\N	4.27.0	\N	\N	2047495707
\.


--
-- Data for Name: databasechangeloglock; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.databasechangeloglock (id, locked, lockgranted, lockedby) FROM stdin;
1	f	\N	\N
\.


--
-- Name: cars_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cars_id_seq', 1, false);


--
-- Name: cars cars_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cars
    ADD CONSTRAINT cars_pkey PRIMARY KEY (id);


--
-- Name: databasechangeloglock databasechangeloglock_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.databasechangeloglock
    ADD CONSTRAINT databasechangeloglock_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

--
-- Database "postgres" dump
--

\connect postgres

--
-- PostgreSQL database dump
--

-- Dumped from database version 16.2
-- Dumped by pg_dump version 16.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: adminpack; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS adminpack WITH SCHEMA pg_catalog;


--
-- Name: EXTENSION adminpack; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION adminpack IS 'administrative functions for PostgreSQL';


--
-- PostgreSQL database dump complete
--

--
-- PostgreSQL database cluster dump complete
--

